source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCWheelView_Example' do
  pod "JCWheelView", :path => "../"
end

target 'JCWheelView_Tests' do
  pod "JCWheelView", :path => "../"
  
end
